create database SQLCase_Study_Basic;
use SQLCase_Study_Basic;


--DATA PREPARATION AND UNDERSTANDING
--the total number of rows in each of the 3 tables in the database
select count(Customer_id) AS [Total in Customer_id] from Customer; 
select count(prod_cat_code)  AS [Total in prod_cat_code] from prod_cat_info;
select count(transaction_id)  AS [Total in transaction_id] from Transactions;


--total number of transactions that have a return


 select count(transaction_id) AS [#Returns] from Transactions
where total_amt like '-%';


-- The dates provided across the datasets are not in a correct format. As first step converted the date variables into valid date formats before proceeding ahead

alter Transactions
alter column Tran_date date;
alter Customer
alter column DOB date;



-- the time range of the transaction data available for analysis? Show the output in number of days, months and years simultaneously in different columns.


SELECT Datediff(year,MIN(tran_date),Max(tran_date)) AS [Year]
,Datediff(MONTH,MIN(tran_date),Max(tran_date)) AS [Month] 
,Datediff(DAY,MIN(tran_date),Max(tran_date)) AS [Day] FROM Transactions;


--product category does the sub-category “DIY” belong to?
select Prod_cat AS Product_Category
from prod_cat_info
where prod_subcat = 'DIY';


--   DATA ANALYSIS

--Which channel is most frequently used for transactions?


select top 1 Store_type AS MOST_USED_CHANNEL from Transactions 
group by Store_type
order by count(store_type)  desc;


--2.	What is the count of Male and Female customers in the database?
 

select Gender, Count(Gender) AS #GENDER from Customer
group by Gender;


--3.	From which city do we have the maximum number of customers and how many?

select TOP 1 CITY_CODE , COUNT(CITY_CODE) AS #CUSTOMERS from Customer
GROUP BY city_code
ORDER BY city_code DESC;

--4.	How many sub-categories are there under the Books category?

SELECT Prod_cat,COUNT(prod_subcat) AS #Sub_Categories FROM prod_cat_info
where prod_cat = 'Books'
GROUP BY prod_cat;

--5.	What is the maximum quantity of products ever ordered?

select max(qty) from Transactions;


--6.	What is the net total revenue generated in categories Electronics and Books? 

SELECT Prod_cat,SUM(TOTAL_AMT) AS TOTAL_REVENUE
FROM Transactions 
JOIN prod_cat_info
ON prod_cat_info.prod_cat_code=Transactions.prod_cat_code
GROUP BY prod_cat
having prod_cat_info.prod_cat='Electronics' OR prod_cat_info.prod_cat= 'Books';


--7.	How many customers have >10 transactions with us, excluding returns?
 

select count(transaction_id) as #transactions
from Transactions
where total_amt not like '-%'
group by cust_id
having count(transaction_id) >10;


--8.	What is the combined revenue earned from the “Electronics” & “Clothing” categories, from “Flagship stores”?



select sum(Total_amt) AS CombinedSales from Transactions as T1 join prod_cat_info as T2
on T1.prod_cat_code = T2.prod_cat_code
where prod_cat = 'Electronics' or prod_cat = 'Clothing' and Store_type = 'Flagship';




--9.	What is the total revenue generated from “Male” customers in “Electronics” category? Output should display total revenue by prod sub-cat.

select * from prod_cat_info;
select * from Customer;
select * from Transactions;
select prod_subcat AS Electronics_M,sum(total_amt) AS ANSWER 
from Transactions as T1  join Customer as T2
on T1.cust_id = T2.customer_Id
join prod_cat_info as T3
on T1.prod_subcat_code = T3.prod_sub_cat_code
where Gender = 'M' and prod_cat = 'Electronics'
group by prod_subcat;


--Q.10.	What is percentage of sales and returns by product sub category; display only top 5 sub categories in terms of sales?


Select top 5 T1.prod_subcat,(Sum(cast (total_amt as float))/ (Select Sum(cast (total_amt as float)) as totalsales from Transactions where Qty > 0)) as Percentageof_sales
from prod_cat_info T1
inner join Transactions T2 on T1.prod_cat_code = T2.prod_cat_code and T1.prod_sub_cat_code = T2.prod_subcat_code
where Qty > 0
group by prod_subcat



--11.	For all customers aged between 25 to 35 years find what is the net total revenue generated by these consumers in last 30 days of transactions from max transaction date available in the data?


Select cust_id, DATEDIFF(YEAR,DOB,max_date) AS Age ,revenue from (
select T2.cust_id,DOB,max(CONVERT(Date,T2.tran_date, 105))as max_date,Sum(cast (total_amt as float)) as revenue
from Customer T1
inner join Transactions T2 on T1.customer_Id = T2.cust_id
where Qty > 0
group by T2.cust_id,DOB
) as A



--12.	Which product category has seen the max value of returns in the last 3 months of transactions?


select T1.prod_cat,T2.Store_type,count(t2.Store_type) as storetype
from prod_cat_info as T1
inner join Transactions as T2 on T1.prod_cat_code = T2.prod_cat_code
Group by T1.prod_cat,T2.Store_type


--13.	Which store-type sells the maximum products; by value of sales amount and by quantity sold?
 

select Store_type, Sum(cast (total_amt as float)) As Revenue,sum(cast (Qty as float))  as quantity
from Transactions
where Qty > 0
group by Store_type
order by Revenue desc , quantity desc

--14.	What are the categories for which average revenue is above the overall average.


select prod_cat_code,Avg(cast (total_amt as float)) As Avg_Revenue
from Transactions
where Qty > 0
group by prod_cat_code
having Avg(cast (total_amt as float)) >= (select Avg(cast (total_amt as float)) As Avg_Revenue from Transactions where Qty > 0)


--15.	Find the average and total revenue by each subcategory for the categories which are among top 5 categories in terms of quantity sold.


select prod_cat_code,Sum(cast (total_amt as float)) As Revenue,Avg(cast (total_amt as float)) As Avg_Revenue
from Transactions
where Qty > 0 and prod_cat_code in ( select top 5  prod_cat_code  from Transactions  where Qty > 0  group by prod_cat_code 
order by sum(cast (Qty as float)) desc)
group by prod_cat_code















